#!/bin/bash
# rclone-jobs v{{VERSION}} - regenerate /etc/cron.d/rclone-jobs from $BOOT_DIR/jobs/*.conf
#
# This script owns EXACTLY ONE file: /etc/cron.d/rclone-jobs (override: RJ_CRON_FILE).
# /etc/cron.d/root and every other cron file are never touched (Dynamix keeps those).
#
# usage:
#   regen-cron.sh            write the file (idempotent: no rewrite when content matches)
#   regen-cron.sh --dry      print what WOULD be written; change nothing
#   regen-cron.sh --check    exit 0 if the installed file matches, exit 1 + drift on stdout
#
# Exit: 0 ok, 1 drift (--check) or at least one invalid job config (line skipped, logged).
set -uo pipefail
NAME="rclone-jobs"
BOOT_DIR="${RJ_BOOT_DIR:-/boot/config/plugins/rclone-jobs}"
EMHTTP_DIR="${RJ_EMHTTP_DIR:-/usr/local/emhttp/plugins/rclone-jobs}"
CRON_FILE="${RJ_CRON_FILE:-/etc/cron.d/rclone-jobs}"

log() { printf '%s\n' "$*" >&2; }

# whitelist parser (never sourced/eval'd) - only STORAGE_ROOT is needed here
storage_root() {
  local v="" line key val
  if [ -f "$BOOT_DIR/paths.env" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
      line="${line%$'\r'}"
      case "$line" in ''|'#'*) continue ;; esac
      case "$line" in *=*) ;; *) continue ;; esac
      key="${line%%=*}"; val="${line#*=}"
      val="${val#\"}"; val="${val%\"}"
      [ "$key" = "STORAGE_ROOT" ] && v="$val"
    done < "$BOOT_DIR/paths.env"
  fi
  [ -n "${RJ_STORAGE_ROOT:-}" ] && v="$RJ_STORAGE_ROOT"
  if [ -z "$v" ]; then
    local d src
    for d in /mnt/disk[0-9]*; do
      [ -d "$d" ] || continue
      src="$(findmnt -no SOURCE -T "$d" 2>/dev/null)" || continue
      case "$src" in /dev/md*) v="$d/.$NAME"; break ;; esac
    done
  fi
  printf '%s' "$v"
}

engine_path() { # prefer the emhttp copy (exists even before storage guard), fall back to CLI copy
  local e="$EMHTTP_DIR/engine/rclone-jobs.sh" s
  [ -x "$e" ] && { printf '%s' "$e"; return 0; }
  s="$(storage_root)/rclone-jobs.sh"
  [ -x "$s" ] && { printf '%s' "$s"; return 0; }
  printf '%s' "$e"
}

re_sched='^[0-9,*/-]+( [0-9,*/-]+){4}$'
re_name='^[A-Za-z0-9_-]{1,40}$'

out="$(mktemp)" || { log "$NAME regen: mktemp failed"; exit 1; }
{
  echo "# managed by $NAME - do not edit; regenerated by regen-cron.sh (plugin save / array_started)"
  echo "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
} > "$out"

errs=0
eng="$(engine_path)"
for f in "$BOOT_DIR/jobs"/*.conf; do
  [ -e "$f" ] || continue
  n="$(basename "$f" .conf)"
  if ! [[ "$n" =~ $re_name ]]; then log "$NAME regen: SKIP $(basename "$f"): invalid job name"; errs=1; continue; fi
  sched=""; en="yes"
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%$'\r'}"
    case "$line" in ''|'#'*) continue ;; esac
    case "$line" in *=*) ;; *) continue ;; esac
    key="${line%%=*}"; val="${line#*=}"
    val="${val#\"}"; val="${val%\"}"
    case "$key" in
      SCHEDULE) sched="$val" ;;
      ENABLED)  en="$val" ;;
    esac
  done < "$f"
  [ "$en" = "no" ] && continue
  if [ -z "$sched" ]; then log "$NAME regen: SKIP $n: enabled but no SCHEDULE"; continue; fi
  if ! [[ "$sched" =~ $re_sched ]]; then log "$NAME regen: SKIP $n: invalid SCHEDULE '$sched'"; errs=1; continue; fi
  echo "$sched root /usr/bin/env bash '$eng' run $n 2>&1 | /usr/bin/logger -t $NAME" >> "$out"
done

case "${1:-}" in
  --dry)
    cat "$out"; rm -f "$out"; exit "$errs" ;;
  --check)
    if [ -f "$CRON_FILE" ] && cmp -s "$CRON_FILE" "$out"; then
      rm -f "$out"; exit 0
    fi
    if [ -f "$CRON_FILE" ]; then diff "$CRON_FILE" "$out" | head -20
    else echo "(no $CRON_FILE installed)"; fi
    rm -f "$out"; exit 1 ;;
  "" ) : ;;
  *) log "usage: $0 [--check|--dry]"; rm -f "$out"; exit 1 ;;
esac

if [ -f "$CRON_FILE" ] && cmp -s "$CRON_FILE" "$out"; then
  rm -f "$out"
  echo "$NAME regen: $CRON_FILE already in sync"
  exit "$errs"
fi
if ! cp "$out" "$CRON_FILE" 2>/dev/null; then
  log "$NAME regen: CANNOT write $CRON_FILE"
  rm -f "$out"; exit 1
fi
chmod 0644 "$CRON_FILE" 2>/dev/null
rm -f "$out"
echo "$NAME regen: wrote $CRON_FILE"
exit "$errs"
